<?xml version="1.0" encoding="utf-8"?><Database Name="DB_SPA" Class="LoginDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=DB_SPA;User ID=sa" SettingsObjectName="SpaClassLibrary.Properties.Settings" SettingsPropertyName="DB_SPAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[USER]" Member="USERs">
    <Type Name="USER">
      <Column Name="ID_USER" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ROLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ROLE_USER" Member="ROLE" ThisKey="ID_ROLE" OtherKey="ID_ROLE" Type="ROLE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ROLE" Member="ROLEs">
    <Type Name="ROLE">
      <Column Name="ID_ROLE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ROLE_USER" Member="USERs" ThisKey="ID_ROLE" OtherKey="ID_ROLE" Type="USER" />
    </Type>
  </Table>
</Database>